### ISSUE TITLE
Is flask-macaroons still being worked on?

### ISSUE THREAD

**Issue by bhargavrpatel** [mattccrampton/flask-macaroons#1]
I see that the last commit on this repository is 4 years ago. I am wondering if this project is still being actively developed.

**Comment by mattccrampton** [comment]
@bhargavrpatel apologies, it is not being worked on.  Is it something you want to work on?

**Comment by bhargavrpatel** [comment]
Yes I would love to!

**Comment by mattccrampton** [comment]
@bhargavrpatel Awesome, just added you
